apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobhander
spec:
  selector:
    matchLabels:
      app: jobhandler
      env: develop
  replicas: 1
  template:
    metadata:
      labels:
        app: jobhandler
        env: develop
    spec:
      containers:
      - name: hpa-demo
        image: 694201337911/hpa-demo:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: RUST_LOG
          value: "info"
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80
