apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jobhander
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jobhander
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
